name: pakapaka
description: "Sharing your stories."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  easy_localization: ^3.0.7+1
  flutter_riverpod: ^2.6.1
  fluentui_system_icons: ^1.1.273
  logger: ^2.5.0
  flutter_native_splash: ^2.4.4
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  crypto: ^3.0.6
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
