name: pacapaca
description: "Sharing your stories."
publish_to: "none"
version: "1.0.3"

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  easy_localization: ^3.0.7+1
  flutter_riverpod: ^2.6.1
  fluentui_system_icons: ^1.1.273
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  crypto: ^3.0.6
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  go_router: ^14.8.0
  flutter_screenutil: ^5.9.3
  sign_in_with_apple: ^6.1.4
  dio: ^5.8.0+1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  freezed_annotation: ^2.4.4
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  timeago: ^3.7.0
  share_plus: ^10.1.4
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2
  shimmer: ^3.0.0
  in_app_purchase: ^3.2.1
  in_app_purchase_android: ^0.4.0
  in_app_purchase_storekit: ^0.3.21
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  profanity_filter: ^2.0.0
  google_sign_in: ^5.4.4
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/profiles/
    - assets/icon/
    - assets/data/
    - .env

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
